var.default SOLR_INIT_SCRIPT "${BASE_DIR}/bin/jetty"
var.default SOLR_HOME "${BASE_DIR}/solr"
var.default SOLR_HOST "${BASE_DOMAIN}"
var.default SOLR_PORT "9002"
var.default SOLR_PID "${PID_DIR}/solr"
var.default SOLR_LOGS "${LOG_DIR}/solr"
